### PR TITLE
`CircleMarker` Performance Optimizations

### PR DESCRIPTION
**Pull request by Alexays**
I'm working on a project that requires a map with a lot of elements, while maintaining optimum performance.
At the moment, we have one custom painter per circle, which leads to a huge drop in performance when there are thousands of circles, for example, whereas we could just as easily use a single painter.

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
Hi @Alexays, thanks for your PR!

We'll have a look into this, as performance improvements are always welcome. However, the tests are now failing.

**Comment by Alexays** [comment]
> Hi @Alexays, thanks for your PR!
> 
> We'll have a look into this, as performance improvements are always welcome. However, the tests are now failing.

Thanks!
Tests should be ok now.

**Comment by Alexays** [comment]
Just pushed another improvements.
As accorded to Hixie here
https://www.reddit.com/r/flutterhelp/comments/oa5dh3/is_there_a_way_to_cache_a_portion_of_canvas_to/
The use of drawPoints is way faster, and it allows us to draw the same circles in batch.
I just added a group logic to keep the border and color functionalities different.
And in my tests, I finally reached 60 fps with ~10000 circles drawn vs ~12fps with the old implementation.

**Comment by JaffaKetchup** [comment]
Wow that's an improvement and a half! I'll check later today. 

To be honest, circle markers have not had much work done to them since their introduction.

**Comment by TesteurManiak** [comment]
Thanks for the contribution! Do you think you can also update the `CirclePage` example to showcase your improvements with a lot of circles? This will make it easier to test.

**Comment by JaffaKetchup** [comment]
(maybe follow the pattern from Many Markers?)

**Comment by Alexays** [comment]
Sure done :)

**Review by TesteurManiak — APPROVED** [review]
LGTM, I've tested the example on Flutter Web with canvaskit and the map was quite smooth even with 20.000 circles 👍

**Comment by JaffaKetchup** [comment]
Many thanks :)

**Pull request merged**
