### PR TITLE
Fix mbTilesToPngs

### PR DESCRIPTION
**Pull request by paolorotolo**

### CODE REVIEW

**Review by ibrierley — APPROVED** [review]
lgtm

**Review by JaffaKetchup — APPROVED** [review]
Simple README fix. LGTM.

**Comment by JaffaKetchup** [comment]
Ready to merge.

This is a documentation update: please note #992 which will eventually improve documentation and may or may not replace the README. Therefore, if applicable, this change will also be carried (in the best way possible) to the new documentation.

**Comment by JaffaKetchup** [comment]
Note that checks are currently failing for unrelated reasons.

**Pull request merged**
