### PR TITLE
add vector_map_tiles plugin to readme

### PR DESCRIPTION
**Pull request by greensopinion**
I'd like to add vector_map_tiles to the readme so that it's more discoverable.

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
This looks very useful and would definitely widen the possibilities!
Although, I would like to see a way to use existing tile providers, so that this plugin could be used with another plugin that provides a provider (let's say my offline one for example), but I'm not sure if this is possible?

**Comment by greensopinion** [comment]
@JaffaKetchup thanks for the suggestion. I did look at that however [`TileProvider`](https://github.com/fleaflet/flutter_map/blob/master/lib/src/layer/tile_provider/tile_provider.dart#L11) is all about tiles as images, whereas this is all about vector tiles, which are not images.

**Comment by ibrierley** [comment]
I concur with that, I took at look at using the existing tile providers for my vector stuff, and it felt like banging a square peg in a round hole (was looking at a separate codec decode and things like that). The alternative felt like trying to change some of the core code, which felt like a bad idea.

**Comment by JaffaKetchup** [comment]
Yeah, fair enough!

**Review by ibrierley — COMMENTED** [review]
Fine with me, it shows it's current status on the readme, and I've tested it, so I think should be included.

**Comment by greensopinion** [comment]
bumping this so it doesn't get automatically closed - would be great to get this in!

**Comment by JaffaKetchup** [comment]
Definitely!

________________________________

**Comment by JaffaKetchup** [comment]
@greensopinion Please see https://github.com/greensopinion/flutter-vector-map-tiles/issues/11

**Review by kengu — APPROVED** [review]
LGTM. Thanks for the contribution!

**Comment by greensopinion** [comment]
nice, thanks!

**Comment by JaffaKetchup** [comment]
@greensopinion Your plugin has now also been added to the WIP documentation as discussed:
https://flutter-map.vercel.app/plugins/list#:~:text=vector_map_tiles%20by%20greensopinion

**Comment by greensopinion** [comment]
great!

**Pull request merged**
