### PR TITLE
chore: add image to pubspec.yaml

### PR DESCRIPTION
**Pull request by josxha**
This pr is a proposal to add the fm logo as image to the pubspec.yaml file.

The result would look similar to here and further improve the package visibility on pub.dev:
image

The image resolution is currently in this pr only 200x200px as this was the biggest that I could find.

### CODE REVIEW

**Review by JaffaKetchup — APPROVED** [review]
LGTM. Just be aware that this is not recommended practise, but I'm fine with it:

https://dart.dev/tools/pub/pubspec#screenshots
> Don't include logos or other branding imagery in this section.

**Comment by josxha** [comment]
>Also just be aware that [this is not recommended practise](https://dart.dev/tools/pub/pubspec#screenshots), but I'm fine with it.

Yep, red that too but tbh I think the logo fits better than some ordinary screenshot. 😄

**Comment by JaffaKetchup** [comment]
> "summary": "### [*] 0/10 points: Package has an example and has no issues with screenshots\n\nFound 4 issues. Showing the first 2:\n\n* `/tmp/pana_TLPLCL/./images/logo.webp`: Tried interpreting screenshot as WebP with `webpinfo \"/tmp/pana_TLPLCL/./images/logo.webp\"` failed with _exit code_ `2`.\n* `/tmp/pana_TLPLCL/./images/logo.webp`: Converting screenshot with `cwebp \"/tmp/pana_TLPLCL/./images/logo.webp\" -o \"/tmp/ICOKKH/gen/logo.webp\"` failed with _exit code_ `2`."

Not sure what to make from that.

**Comment by josxha** [comment]
Closing this pr, because of the valid concerns with the current fleaflet logo. Need to revisit once we have one.

**Pull request closed without merging**
