### PR TITLE
Add `minZoom` property to `FitBoundsOptions`

### PR DESCRIPTION
**Pull request by Robbendebiene**
The `centerZoomFitBounds` is a very powerful method and can be used for a lot of different use cases.

Sometimes one doesn't only want to limit the `maxZoom` but the `minZoom` level. For example to ensure, that we won't zoom out past a certain zoom level even if this means that the supplied bounds won't fit entirely within.

Clamping the zoom afterwards doesn't work, because the center calculation depends on it.

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
Hey @Robbendebiene, thanks for the contribution, it certainly looks like something we'd like to have, and the code looks LGTM I think. I just need to give it a quick test, which I should be able to do in the next few days.

At this time, #1551 is taking priority over all other PRs, as it implements significant breaking changes.
@rorystephenson If this is merged prior to #1551, do you think you could integrate it/resolve conflicts? Alternatively, @Robbendebiene, would you be more comfortable resolving conflicts on your side after #1551 is merged (not 100% sure of an ETA for that yet, but should be within the next week or two)?
Don't mind either way, whatever you guys feel more comfortable is fine by me.

**Comment by Robbendebiene** [comment]
Hi @JaffaKetchup, I think integrating this one way or the other should be rather trivial. So I don't mind resolving conflicts after https://github.com/fleaflet/flutter_map/pull/1551 has landed.

**Comment by JaffaKetchup** [comment]
Ok, I'll set this as draft for now then, waiting for #1551 to be merged.

**Comment by JaffaKetchup** [comment]
Hey @Robbendebiene, if you're around, can you resolve the conflicts please? #1551 has been merged.

**Comment by Robbendebiene** [comment]
Sorry, I accidentally closed this PR. I'm working on the updates.

**Comment by Robbendebiene** [comment]
@JaffaKetchup So this is tested and ready for review from my end :)

**Review by JaffaKetchup — APPROVED** [review]
LGTM, thanks for your contribution!

**Pull request merged**
