### PR TITLE
Cancel animations on map controller move events

### PR DESCRIPTION
**Pull request by Robbendebiene**
This fixes https://github.com/fleaflet/flutter_map/issues/946

Fling and double tap animations are already cancelled in multiple scenarios (like panning the map). This PR also cancels the animations whenever the `MapController` moves the camera. This is done to prevent interferences with animated camera moves.

### CODE REVIEW

**Comment by Robbendebiene** [comment]
I still like to land this PR.

**Comment by b3nni97** [comment]
Can someone review this?

**Comment by Robbendebiene** [comment]
@johnpryan or @kengu can you please review this.

**Comment by b3nni97** [comment]
Is this repository abandoned?

**Comment by ibrierley** [comment]
Sorry about all of the delay, there's a bit more action now. There's been some changes since, but if you can pull upstream when possible, then we'll see if we can get it tested and merged!

**Comment by JaffaKetchup** [comment]
@b3nni97 No! There have been some developments recently after a quiet period, hopefully it doesn't happen again.

**Comment by Robbendebiene** [comment]
@ibrierley and @JaffaKetchup I've just pulled upstream.

**Comment by JaffaKetchup** [comment]
Ok, thanks. Just needs to be reviewed before merge. I can't check it over for another 8 hours or so (I'm currently on mobile), but maybe another maintainer can!

**Review by ibrierley — APPROVED** [review]
Testing seems good. I note on the mapController page it now takes you to the correct location if mid fling and a different location selected, so happy with that.Thanks!

**Comment by ibrierley** [comment]
Happy to merge this, but not sure if you wanted to do any testing first @JaffaKetchup

**Comment by JaffaKetchup** [comment]
No it's ok, I trust your judgement. Please do merge!

**Comment by ibrierley** [comment]
Ah sorry missed your last comment.

**Comment by JaffaKetchup** [comment]
Nah no problem! It was only 2 commits anyway. I just prefer squashing for PRs with lots of commits: it keeps the main branch tidy.

**Comment by ibrierley** [comment]
Yep, makes sense.

**Comment by alanlanglois** [comment]
I made a custom move animation to center the map on current location when pressing a button.
When I pan and click the recenter button while the kinetic Pan animation is not finished, the recenter animation play as it should, but when finished it flick to what I guess is the end of the kinetic animation.
demo

**Comment by ibrierley** [comment]
are you using the latest version from Git (not the one from pub.dev ?)

**Comment by alanlanglois** [comment]
@ibrierley I'm using the one on pub.dev ( flutter_map: ^0.14.0 )

**Comment by ibrierley** [comment]
Ok, it may be worth trying the Git version for you then. I think that may have been fixed, but there could be circumstances where it isn't still (or I'm remembering wrong!).

**Comment by alanlanglois** [comment]
@ibrierley need to do more intensive tests, but looks like it fixies the bug!
When do you plan to land the next version including this fix?

**Comment by ibrierley** [comment]
We currently have no estimation, as it's a bit complicated, but something
we are exploring.

**Comment by JaffaKetchup** [comment]
Please see #1188 for more information about publishing to pub.dev. As @ibrierley said, there is currently no estimate.

**Pull request merged**
