### PR TITLE
Add specs for utility functions

### PR DESCRIPTION
**Pull request by comatory**

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
Looks like the first two commits are also present in #1144.

**Review by JaffaKetchup — APPROVED** [review]
Changes to internal documentation. Changes to tests. LGTM.

Not sure about what will happen in regards to the first two commits also being present in #1144, which also needs to be merged? @comatory or @johnpryan or any other maintainer, do you have an idea?

**Comment by comatory** [comment]
It doesn't matter which one we merge first, I can rebase & deal with conflicts and push again.

**Comment by JaffaKetchup** [comment]
Ok, will merge this first.

Note, this is also present in the 'Documentation Improvements' (#992), but is being merged here now as it does not necessarily need to wait for the rest of the improvements.

**Comment by comatory** [comment]
On Sat Jan 29, 2022 at 4:09 PM CET, Luka S wrote:
> Ok, will merge this first.
>
> Note, this is also present in the 'Documentation Improvements' (#992), but is being merged here now as it does not necessarily need to wait for the rest of the improvements.
>

Should be OK I think, if this gets to `master`, the other PR's branch
will get updated (either via web interface or locally with git).

Unless there would be some conflicts.

**Pull request merged**
