### PR TITLE
Added latLngToScreenPoint and refactored pointToLatLng

### PR DESCRIPTION
**Pull request by ibrierley**
Recreation of PR #1325 due to issues.

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
'due to issues' :D 
Happy to approve if you're happy!

**Comment by ibrierley** [comment]
It fails on some lint stuff zzz :D, so leave for the moment, maybe something else hasn't copied over or something as well.

**Comment by ibrierley** [comment]
hmm I don't really know what's happening, so not sure I trust any of this :D. Checks seem to fail on lints, but the line numbers it's referencing seem to be on old versions of files. Is it possible somehow lints use some caching ?

**Comment by JaffaKetchup** [comment]
Let me take a look, it might be 'my' new package scorer being annoying.

**Comment by JaffaKetchup** [comment]
The latest commit seems to have passed.

**Comment by ibrierley** [comment]
ok curious, I keep getting an email saying its failed, but that's on my repo (thought they were normally done on fm), so maybe something else is confused somewhere on my side. 

If the test page all runs fine, and you can't spot any errors, then feel free to approve or merge.

**Comment by ibrierley** [comment]
oh, maybe we want a minor version increase as well as the other version was released since ?

**Review by JaffaKetchup — APPROVED** [review]
LGTM. We don't need a version change: I've got #1324 for that.

**Comment by JaffaKetchup** [comment]
Interestingly, I can't see the checks passing here anymore, but I can see the green checkmark on your repo, so it should be OK. Just need to pay attention to that in the future.

**Comment by ibrierley** [comment]
Super, thanks.

**Pull request merged**
