### PR TITLE
Added possibility to override double tap behaviour

### PR DESCRIPTION
**Pull request by FaFre**
Simple option to override the default double tap behavior (zoom), to implement an own animation or functionality.

### CODE REVIEW

**Comment by deckerst** [comment]
Exactly what I need. Is there any reason why this tiny PR was not reviewed and merged?

**Comment by juarezfranco** [comment]
+1

**Comment by ibrierley** [comment]
If you want to do a pull upstream as there's been a few changes since, we'll test and look to get it merged if all ok now, thanks!

**Comment by FaFre** [comment]
@ibrierley done

**Comment by FaFre** [comment]
@ibrierley any news on this?

**Comment by ibrierley** [comment]
Sorry, I had missed this. I will check when back probably tomorrow

**Comment by ibrierley** [comment]
Just testing this...I seem to get the error...
```
error - lib/src/gestures/gestures.dart:595:27 - 2 positional argument(s) expected, but 1 found. Try adding the missing arguments. - not_enough_positional_arguments
  error - lib/src/gestures/gestures.dart:595:28 - The argument type 'LatLng' can't be assigned to the parameter type 'TapPosition'. - argument_type_not_assignable
```

It could be because there's been some changes again since, and you may need to pull upstream and test/merge (I will keep a closer eye on any changes submitted)? But I can't quite dig out where it's got that from....

**Comment by ibrierley** [comment]
Thinking about it, it's probably because TapCallback is a typedef TapCallback = void Function(TapPosition tapPosition, LatLng point);
so the call would need to match those parameters ?

**Comment by JaffaKetchup** [comment]
I'm going to close this PR due to inactivity. I'll be happy to reopen it if necessary!

**Pull request closed without merging**
