### PR TITLE
Pinchzoom regarding gesture center

### PR DESCRIPTION
**Pull request by Zzerr0r**
old behaviour on pinchzoom was to zoom in regarding the map center. now it zooms in regarding the center of the pinch gesture like in google maps for example. I didn't add an option to change between the two as i cant imagine anyone would want to zoom into the center of the map when using pinchzoom.

### CODE REVIEW

**Review by ibrierley — APPROVED** [review]
Was looking at this issue today. I think this PR looks good, feels a lot more intuitive and can't see any negatives.

**Comment by JaffaKetchup** [comment]
@Zzerr0r Please pull upstream when possible, then I (or another maintainer) can merge after running the checks.

**Comment by JaffaKetchup** [comment]
@Zzerr0r Please pull upstream, so I can run the checks. Then this should be ready to go! Otherwise, I will have to close this pull request due to inactivity,

**Comment by Zzerr0r** [comment]
I'm sorry, I don't really know how to do that, couldn't you just integrate the changes manually? it's only like 4 lines of code in one file

**Comment by JaffaKetchup** [comment]
@Zzerr0r 
I can if you can't, but it's simple I think.

1. Go to your fork and branch.
2. Look at the bar where it says "This branch is x commits ahead, y commit behind fleaflet:master"
3. Click "Fetch upstream", then "Fetch and merge"

If your not confident enough, edit this PR (in the PR options) to allow edits by maintainers.

**Comment by JaffaKetchup** [comment]
@Zzerr0r 
Thanks for doing that. Now I can see that there are some formatting issues in the file you changed. This should be a simple fix: could you please run `dart format --fix` in your console on the branch. When the checks don't fail, I will merge ASAP, as there is already a review.

**Comment by Zzerr0r** [comment]
No worries at all, glad I could help, I just didn't really know what to do for a while for pulling upstream. I'm super thankful that this library exists and I feel cool contributing. I also think It's super nice that you're active now again! Thanks :)

**Comment by JaffaKetchup** [comment]
Thanks for your contribution, it's greatly appreciated!

**Pull request merged**
