### PR TITLE
feat(LatLngBounds): Center LatLng getter

### PR DESCRIPTION
**Pull request by kevinpthorne**
A `LatLngBounds` object can now return its center midpoint.

Example usage:
```dart
var bounds = LatLngBounds.fromPoints([LatLng(1, 1), LatLng(0, -1)]);
print(bounds.center);
// LatLng(latitude:0.500076, longitude:-0.000076)
```

[The resource used for the maths](http://www.movable-type.co.uk/scripts/latlong.html)

### CODE REVIEW

**Comment by RicardoRB** [comment]
This is great!

**Review by RicardoRB — APPROVED** [review]

**Review by johnpryan — APPROVED** [review]

**Comment by kevinpthorne** [comment]
Did I miss anything for the merge?

**Comment by kevinpthorne** [comment]
GitHub is acting weird. New commit fixed the variable naming conventions

**Review by kengu — APPROVED** [review]
LGTM. Thanks for the contribution!

**Pull request merged**
