### PR TITLE
feat(example): migrate to wasm

### PR DESCRIPTION
**Pull request by josxha**
## Instructions
1. Switch to the beta channel `flutter channel beta`
2. Build for web assembly `flutter build web --help`
3. (optional) Install a dart web server `flutter pub global activate dhttpd`
4. Run the wasm app
```bash
cd build/web
dhttpd '--headers=Cross-Origin-Embedder-Policy=credentialless;Cross-Origin-Opener-Policy=same-origin'
```

## Roadmap
- [x] migrate example app
- [ ] `flutter_map_cancellable_tile_provider` doesn't work with wasm yet
```console
DioException [unknown]: null
Error: Unsupported operation: Platform._version
```
- [ ] update CI

## Links and Resources
- https://docs.flutter.dev/platform-integration/web/wasm

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
We may want to hold off on this for a little while: https://docs.flutter.dev/platform-integration/web/wasm#known-limitations.

**Comment by mdmm13** [comment]
> We may want to hold off on this for a little while: https://docs.flutter.dev/platform-integration/web/wasm#known-limitations.

Maybe merge as `index-wasm.html` so those experimenting with WASM can have a go? 

The Flutter team is expecting to have complete WASM support [this year](https://github.com/flutter/flutter/wiki/Roadmap#web-platform) and judging by the number of PRs they've been merging on the topic recently, I'd assume not in the last release of the year. Let's see if it's the game changer we're hoping for on web.

**Comment by josxha** [comment]
> We may want to hold off on this for a little while [...]

Agree, I would even delay the merge until wasm is stable. This pull request can be considered for testing purposes (and to migrate the cancellable tile provider until then).

> Maybe merge as index-wasm.html so those experimenting with WASM can have a go?

flutter_map is compatible with wasm out of the box since its code is dart-only. All migration that was needed is in the example app. You can just pull the wasm branch if you want to test flutter_map on wasm.

**Comment by mdmm13** [comment]
> > We may want to hold off on this for a little while [...]
> 
> Agree, I would even delay the merge until wasm is stable. This pull request can be considered for testing purposes (and to migrate the cancellable tile provider until then).

I'm going to try to foresee the future here, but I have a feeling Flutter Wasm will be going stable tomorrow 💡🚀

image

**Comment by JaffaKetchup** [comment]
Hmm, not sure 🤔. Maybe give it another year :D

I guess they're releasing it so they can announce it at Google I/O, which I was guessing would happen!

**Comment by mdmm13** [comment]
> Hmm, not sure 🤔. Maybe give it another year :D
> 
> I guess they're releasing it so they can announce it at Google I/O, which I was guessing would happen!

Along with [Flutter 3.22](https://docs.flutter.dev/release/release-notes), which brings lots of Impeller improvements also.

**Comment by JaffaKetchup** [comment]
Not sure if this was here before:

> Even with the --wasm flag, flutter build web will still compile the application to JavaScript. If WasmGC support is not detected at runtime, the JavaScript output is used so the application will continue to work across browsers.

But it might be safe to do this now! Might need to do a fresh create of the web build config though.

**Pull request closed without merging**
