### PR TITLE
Fixed `CircleMarker`'s incorrect appearance and size

### PR DESCRIPTION
**Pull request by Alexays**
Fix https://github.com/fleaflet/flutter_map/issues/1688

- Radius instead of diameters
- Fixed circles with only borders/filled with a transparent color

### CODE REVIEW

**Review by JaffaKetchup — CHANGES_REQUESTED** [review]
That doesn't quite look like a circle to me 😂! Did you forget something or is this not ready for review yet?

image

**Comment by Alexays** [comment]
Oups sorry, fixed! @JaffaKetchup

**Comment by algizmonaco** [comment]
Hi

just tried the demo and the circle still does not fill correctly. When zooming it works partially.

Regards Daniel

**Comment by JaffaKetchup** [comment]
Hi @algizmonaco,
I see you're running on iOS, can you try disabling Impeller to see if that resolves the issue?

**Comment by algizmonaco** [comment]
thx,

Disabling Impeller fixes the issue. keeping disabled until it is fixed. May you want to add this to readme. thx

Daniel

**Comment by JaffaKetchup** [comment]
I believe the fix is already available on Flutter's 'master' branch, so hopefully it won't take too long to arrive!

**Pull request merged**
