### PR TITLE
fix: remove final from none-final fields

### PR DESCRIPTION
**Pull request by andreandersson**

### CODE REVIEW

**Comment by andreandersson** [comment]
@johnpryan I believe this is very important to merge and release asap, since flutter_map basically can't be used in the latest release.

**Comment by rorystephenson** [comment]
It's probably worth linking the issue: https://github.com/fleaflet/flutter_map/issues/922

**Comment by TheOneWithTheBraid** [comment]
Should definitely be merged very soon.

**Comment by JaffaKetchup** [comment]
This needs to be merged quickly. This sort of thing should be tested before a major release.

**Comment by kengu** [comment]
@JaffaKetchup We should try to make some more tests to automate detection of regressions

**Review by kengu — APPROVED** [review]
LGTM

**Pull request merged**
