### PR TITLE
Added TapPosition to TapCallback

### PR DESCRIPTION
**Pull request by m-oehme**
This PR added the Screens TapPosition to the onTap Callback. 

When using an interactive WFS Service that handles Click/Touch Inputs you need to pass the Screen Position to Pressed to the Service, not the LatLong point.
If you use a separate GestureDetector stacked on top of FlutterMap it interferes with its Gestures (like Pan oder Pinch). This PR exposes the TapPosition from FlutterMaps own GestureDetector.

Related to https://github.com/fleaflet/flutter_map/issues/706

### CODE REVIEW

**Review by mauriceraguseinit — APPROVED** [review]
looks good to me

**Comment by kengu** [comment]
@m-oehme LGTM. There are four code errors however. Can ut update the code and commit the changes?

**Comment by m-oehme** [comment]
@kengu thanks I didn't see that one

**Review by kengu — APPROVED** [review]
LGTM. Thank's for the contribution!

**Comment by znromonk** [comment]
Ever since this was merged (ver 0.14.0), I get the error at the onTap callback.

> Error: The argument type 'void Function(TapPosition)' can't be assigned to the parameter type 'void Function(TapPosition, LatLng)?'.
>  - 'TapPosition' is from 'package:positioned_tap_detector_2/positioned_tap_detector_2.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/positioned_tap_detector_2-1.0.0/lib/positioned_tap_detector_2.dart').
>  - 'LatLng' is from 'package:latlong2/latlong.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/latlong2-0.8.1/lib/latlong.dart').

Code causing the issue:
```
FlutterMap(
  mapController: _mapController,
  options: MapOptions(
    bounds: _mapBounds,
    boundsOptions: FitBoundsOptions(padding: EdgeInsets.all(100)),
    onTap: (_) {
      _mapController.fitBounds(_mapBounds,
          options:
              FitBoundsOptions(padding: EdgeInsets.all(100)));
    },
  layers: [
    TileLayerOptions(
      urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
      subdomains: ['a', 'b', 'c'],
      attributionBuilder: (_) {
        return Text("© OpenStreetMap contributors");
      },
    ),
  ],
}
```

flutter doctor -v
<details>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.5.1 at /Users/menon/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (11 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0-rc4)
    • Android SDK at /Users/menon/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0-rc4
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • iPhone 12 Pro Max (mobile) • 5E37824C-09FC-40D9-8A0C-CFA8AC858554 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google
      Chrome 93.0.4577.82

• No issues found!
```
</details>

**Pull request merged**
