### PR TITLE
Fix EPSG4326 parameter difference with Leaflet.js

### PR DESCRIPTION
**Pull request by yeleibo**
image

### CODE REVIEW

**Comment by ibrierley** [comment]
Can you describe what the difference this may make to users that they would notice when testing or using ?

**Comment by yeleibo** [comment]
when map option crs set with EPSG4326,the map load error

**Comment by JaffaKetchup** [comment]
@yeleibo Can you please pull upstream, so I can re-run checks and review (and merge)? Thanks,

**Comment by yeleibo** [comment]
> @yeleibo你能拉到上游，所以我可以重新运行检查和审查（和合并）？谢谢，
 
yes,I already pull upstream！

**Review by JaffaKetchup — APPROVED** [review]
LGTM, new example page seems to work. Bit of an odd projection, never used it before, but I guess this has fixed something. Will merge now...

**Pull request merged**
