### PR TITLE
remove mbtiles tile provider + sqflite dependency

### LINKED ISSUE #786: Can't run example on iOS
```
 flutter run -d iphone
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running pod install...                                              1.4s
Running Xcode build...                                                  
Xcode build done.                                            3.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    In file included from /Users/john/code/sdks/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/ios/Classes/FLTPathProviderPlugin.m:5:
    /Users/john/code/sdks/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.24/ios/Classes/FLTPathProviderPlugin.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target
    'path_provider' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target
    'FMDB' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target
    'location' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.2.99. (in target
    'Flutter' from project 'Pods')
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the
    Runner editor. (in target 'Runner' from project 'Runner')
```

### PR DESCRIPTION
**Pull request by johnpryan**
fixes #786

@avbk The dependency on sqlflite can cause problems for users who want to use flutter_map without the mbtiles provider.  Since this is a map plugin, I think this code should be written as a separate package. That way, you would include flutter_map along with the new package, (e.g. flutter_map_mbtiles) and then use the MBTilesImageProvider from that package. 

Would you like to make that package since you were the original author?

### CODE REVIEW

**Comment by avbk** [comment]
Hey John, good thinking! I didn't consider the plugin system, was it already available back then?

I'm quite busy nowadays, but I'll added it to my todolist and scheduled it for somewhere around xmas and new years eve.

**Comment by johnpryan** [comment]
No worries, it might not have been available when this was added. I was having some trouble running on iOS with sqflite (https://github.com/fleaflet/flutter_map/issues/786) so I'm not sure how much effort it will take.

**Comment by DonWasyl** [comment]
@johnpryan, @avbk  I hope that no one from you guys is angry with me, but I needed this functionality, so I used code and have made a separate package with MBTilesProvider based on removed code from this repository.

https://github.com/DonWasyl/flutter_map_mbtiles_provider

**Comment by johnpryan** [comment]
@DonWasyl these were contributed under a BSD license, so it's okay (from a licensing point of view) to publish it as a package. I would recommend adding a similar license to your package, though.

**Comment by DonWasyl** [comment]
Right.
@johnpryan Are you the author of this part of the code or someone else? I don't want to write that I am the author ;)

**Comment by johnpryan** [comment]
No, I believe these were added by @avbk

**Comment by avbk** [comment]
Awesome, I didn't find any time to rewrite it as a plugin, yet. So I am glad that you put out the existing files on pub!

**Comment by DonWasyl** [comment]
@avbk Can I put this code to pub.dev? 🙂
I put in license `flutter_map authors` as the author. Would you like to put your nickname or real name too?

**Comment by avbk** [comment]
Yeah I'd love to see it on pub!
Sure, it's Alexander von Bremen-Kühne

**Pull request merged**
