### PR TITLE
update vector_map_tiles docs

### PR DESCRIPTION
**Pull request by greensopinion**
Remove reference to mixed mode which
is no longer supported. Minor wording
change to raster vs vector discussion.

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
Thanks @greensopinion,
I'll make the appropriate changes straight in the editor. Can you confirm whether your plugin supports flutter_map v3 and Flutter 3.3.0?
Many thanks!

**Comment by greensopinion** [comment]
Great, thanks! Yes, `flutter_map` v3 is supported.

**Comment by greensopinion** [comment]
Flutter 3.3.0 is supported too.

**Comment by JaffaKetchup** [comment]
Great, I'll add these changes ASAP.

**Comment by JaffaKetchup** [comment]
See commit https://github.com/fleaflet/flutter_map/commit/1dfdc38193c2954bbc8c4471cc3364cb76b987e8. Hope this works for you!

**Pull request closed without merging**
