### PR TITLE
Prepared for release of 0.14.0

### LINKED ISSUE #1021: Release 0.14.0
@johnpryan - Can you release a new version to pub.dev?

### PR DESCRIPTION
**Pull request by kengu**
Closed #1021

### CODE REVIEW

**Review by JaffaKetchup — CHANGES_REQUESTED** [review]
Some pub.dev dependencies can be updated, including but not limited to `async` and `http`. If you're publishing a major version, it would be nice for the dependencies to be updated?

Also resolving major bug #1002 by #1003 would be good.

**Comment by kengu** [comment]
@JaffaKetchup Updated dependencies now. I'm a bit worried about #1002, #1003 and #989. All of them seems a bit hairy. In the case of #989, I think the correct thing to do would is to refactor how the MapState is bootstrapped to remove the async nature of member initialisations. I short, I think we should release what we have, and do a 0.14.1 bugfix release later on. There is a lot of good stuff that shouldn't be held back anymore.

**Review by JaffaKetchup — APPROVED** [review]
OK, I understand that, and I agree. These feature additions are really cool and who knows how long the aforementioned PR's will take.

**Comment by tlueder** [comment]
Hi,

https://github.com/fleaflet/flutter_map/issues/1002 Should be fixed before the release.

As this is a real blocker for me. And it seem that it is a bug from the null safety migration.
Because moveAndRotate uses the id only to call move and rotate, which both don't require a non null id.
Only moveAndRotate does.

**Review by johnpryan — APPROVED** [review]

**Pull request merged**
