### PR TITLE
Center label for polygons

### PR DESCRIPTION
**Pull request by sikandersaleem**
Add labels in center of polygons.

### CODE REVIEW

**Comment by sikandersaleem** [comment]
Hey Travis, there is error on flutter doctor. please check.

**Comment by JaffaKetchup** [comment]
@sikandersaleem Looks good! Can you please pull upstream so that I can take a deeper look after resolving checks? Thanks.

**Comment by JaffaKetchup** [comment]
@sikandersaleem Sorry for the reminder and previous slowness, but please pull upstream. We'd love to have this feature!

**Comment by sikandersaleem** [comment]
Hi dear, i will take pull... Asap, and appologies for being late to reply

**Comment by JaffaKetchup** [comment]
Hi @sikandersaleem. I noticed you haven't fetched upstream yet? Please so, as there feature requests/questions waiting on this.
You should be able to use the 'Fetch upstream' button next to the bar where it says 'x commits behind... X commits in front' on your fork branch.
Thanks.

**Review by JaffaKetchup — CHANGES_REQUESTED** [review]
Hi @sikandersaleem.
I noticed you haven't fetched upstream yet? Please so, as there feature requests/questions waiting on this.
You should be able to use the 'Fetch upstream' button next to the bar where it says 'x commits behind... X commits in front' on your fork branch.
We will also need to resolve conflicts in favour of both changes, which will require more testing.
Many thanks.

**Comment by JaffaKetchup** [comment]
Closing in favour of #1220 due to this PR being inactive.

**Pull request closed without merging**
