### PR TITLE
Add Flutter 3 Compatibility

### LINKED ISSUE #1234: [BUG] Example cannot compile with Flutter 3 on Android
**Describe The Bug**
The example does not build for Android

**Expected Behavior**
The example should build for Android

**Screenshots & Recordings**
```
$ flutter pub cache clean && flutter pub get && flutter run
This will remove everything inside /Users/user/.pub-cache.
You will have to run `flutter pub get` again in each project.
Are you sure? (y/N)? y
Removing pub cache directory /Users/user/.pub-cache.
Running "flutter pub get" in flutter_tools...                       9.1s
Running "flutter pub get" in example...                             4.3s
Launching lib/main.dart on SM G970F in debug mode...
e: /Users/user/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (124, 1): Class 'FlutterLocationService' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: /Users/user/.pub-cache/hosted/pub.dartlang.org/location-4.3.0/android/src/main/java/com/lyokone/location/FlutterLocationService.kt: (258, 5): 'onRequestPermissionsResult' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':location:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Running Gradle task 'assembleDebug'...                              9.9s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Additional Information**
Building for web works fine.

The whole thing was triggered by my upgrade to Flutter 3.0.0.

The root cause appears to be in flutterlocation, see https://github.com/Lyokone/flutterlocation/issues/698 and https://github.com/Lyokone/flutterlocation/issues/718, these issues also discuss workarounds.

This has to be fixed in flutterlocation, I wrote this ticket to avoid unnecessary research effort here ;-)

Changing the compileSdkVersion to 30 does not help.

---

**Doctors Report**

```shell
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-DE)
    • Flutter version 3.0.0 at /Users/hagen/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (3 days ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/hagen/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (4 available)
    • SM G970F (mobile) • XYZ                                          • android-arm64  • Android 12 (API 31)
    • macOS (desktop)   • macos                                         • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)      • chrome                                        • web-javascript • Google Chrome 101.0.4951.64

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**To Reproduce**

`flutter pub cache clean && flutter pub get && flutter run`

---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [x] Non-Fatal
- [ ] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] Others (beta platforms)

### PR DESCRIPTION
**Pull request by JaffaKetchup**
- Fixed example compatibility with Flutter 3: fixes #1234
 - Changed linter rules & fixed other linter errors/warnings
      - Existing rule exceptions were redundant as they were not defined properly and so the analyzer did not parse them
      - Therefore, many of the exceptions' cases were already fixed in a previous PR
      - Added exception for '[library_private_types_in_public_api](https://dart-lang.github.io/linter/lints/library_private_types_in_public_api.html)'

### CODE REVIEW

**Review by ibrierley — COMMENTED** [review]
I think my only problem with this is flutter_lints. Forcing it to ^2.0.1 in the pubspec.yaml (in example and root folder), forces users to upgrade to Flutter3, which feels a bit too soon. Is there any specific reason to require this, and not just have ">=1.0.4" or something ?

**Comment by JaffaKetchup** [comment]
I would agree if it does force Flutter 3 usage then it needs to be changed. But as far as I can see, in both flutter_lints and lints (it's dependency), Flutter 3 usage isn't forced. Maybe I'm misunderstanding something?

https://github.com/flutter/packages/blob/main/packages/flutter_lints/pubspec.yaml
https://github.com/dart-lang/lints/blob/main/pubspec.yaml

**Comment by ibrierley** [comment]
Sorry, yes, it doesn't force 3, but >= 2.17.0 which is ahead of what I typically use 2.15.1 (so guessing others would be similar). I'm not sure whats a minimum most are on.

**Comment by ibrierley** [comment]
Sorry again, that's the Dart version, looks like typically I'm on Dart 2.15.1, flutter 2.8.1,

**Comment by JaffaKetchup** [comment]
Ok, I've relaxed the constraints. Note that the checks use the latest version available every time, so the code formatting must still match those rules, even if an editor may not necessarily warn the developer about those infractions.

**Comment by ibrierley** [comment]
I think flutter_map_example pubspec.yaml needs to be changed as well to match

**Comment by JaffaKetchup** [comment]
I did change the example as well.

**Comment by ibrierley** [comment]
Strange, I can see the files updated in here, but it doesn't seem to be checking the correct version out, maybe something gone astray my end. Will dig.

**Review by ibrierley — APPROVED** [review]
Ok, all good for me now, thanks!

**Pull request merged**
