### PR TITLE
fix screen width and height to degrees conversion when crs is CrsSimple and add double tap callback

### PR DESCRIPTION
**Pull request by neylsongularte**
Crs.pointToLatLng divide pixels by scale and adaptiveBoundaries does not work with CrsSimple.

### CODE REVIEW

**Comment by S-Man42** [comment]
🤟

**Comment by JaffaKetchup** [comment]
Hi @neylsongularte, sorry for the long response time, but I'm quite confused about some of these changes.

Why have the `zoom` variables been replaced with getting the zoom from a `MapController`? Why do we need to:
> Crs.pointToLatLng divide pixels by scale

and what is this code block about:

> ```dart
> var crs = CrsSimple();
>
> LatLng southWest = crs.pointToLatLng(CustomPoint(0, imageHeight), maxZoom)!;
> LatLng northEast = crs.pointToLatLng(CustomPoint(imageWidth, 0), maxZoom)!;
>
> LatLngBounds latLngBonds = LatLngBounds(southWest, northEast);
> ```

Please add some more information to this PR.

**Comment by JaffaKetchup** [comment]
@neylsongularte Sorry to disturb you, but if you have a moment, please fix this pull request and refer to my above comment. No problem if you are unable to, but I will have to close soon :)

**Comment by neylsongularte** [comment]
> Hi @neylsongularte, sorry for the long response time, but I'm quite confused about some of these changes.
> 
> Why have the `zoom` variables been replaced with getting the zoom from a `MapController`? Why do we need to:
> 
> > Crs.pointToLatLng divide pixels by scale
> 
> and what is this code block about:
> 
> > ```dart
> > var crs = CrsSimple();
> > 
> > LatLng southWest = crs.pointToLatLng(CustomPoint(0, imageHeight), maxZoom)!;
> > LatLng northEast = crs.pointToLatLng(CustomPoint(imageWidth, 0), maxZoom)!;
> > 
> > LatLngBounds latLngBonds = LatLngBounds(southWest, northEast);
> > ```
> 
> Please add some more information to this PR.

Hello, I am displaying an image and not a map.

**Comment by JaffaKetchup** [comment]
Might Flutter's `InteractiveViewer` support your needs?

**Pull request closed without merging**
