### PR TITLE
fix: prevent null exception when undefined/null `Polygon.hitValue`

### PR DESCRIPTION
**Pull request by JaffaKetchup**
This works in the polyline layer, but I missed out a line copy when carrying some changes over.
Thanks to @mohammedX6 for bringing this to my attention. Replaces #1826.

### CODE REVIEW

**Review by josxha — APPROVED** [review]
lgtm

Sorry that I haven't seen this in my review. 

edit: will do some additional testing, before I approve 😁

**Comment by josxha** [comment]
When you zoom in far like showcased in the video and then hover over the polygons the app crashes.


https://github.com/fleaflet/flutter_map/assets/34318751/e909d301-abce-4e16-9dd8-d953a130f3d9

Not sure tho if this is related to this bug or another bug.

**Comment by JaffaKetchup** [comment]
Oooh, that's quite nasty, wonder if it's a memory leak or something, or whether the hover outlines are triggering it.

**Comment by JaffaKetchup** [comment]
I can reproduce the increase in frame times, but not the crash (I assume that's device dependent). I'll try and do some more debugging.
 
image

**Comment by JaffaKetchup** [comment]
This is unrelated to tap detection, as it appears to be present prior to the introduction of this. It is present in commit f31829f94d5295ff2f09e7b82671177f1605bc10.
I think this is safe to be reviewed & merged.

**Comment by mohammedX6** [comment]
maybe just setting the `shouldRepaint` to true is the safest option now ?

**Comment by JaffaKetchup** [comment]
Ah, the commit I mentioned above isn't necessarily the commit that caused it, just the previous one that I can reproduce the issue on.

**Comment by JaffaKetchup** [comment]
Report made in #1829.

**Pull request merged**
