### PR TITLE
fix for flickering with fitbounds, moving calculations inside the lay…

### PR DESCRIPTION
**Pull request by ibrierley**
Fix for flickering with fitbounds, moving calculations inside the layoutBuilder…

### CODE REVIEW

**Comment by ibrierley** [comment]
Possible fix for the flickering issue https://github.com/fleaflet/flutter_map/issues/1375. Note this PR will need to proper testing, as I don't experience the issue, so can't verify this properly.

I would also test things like reorientating the device, and on web and emulators as there may well be other issues introduced and this can be quite a fiddly one to fix.

**Comment by mohammedX6** [comment]
It's working fine for me

**Comment by JaffaKetchup** [comment]
@ibrierley You happy to merge this?

**Comment by ibrierley** [comment]
Yes, but as mentioned, I could never replicate the problem, so was hard to know if this has been properly tested. I think it would be good for someone else to test if they get the chance, otherwise just go for it.

**Comment by JaffaKetchup** [comment]
Ok. @stx Can you also give this a test when you get a moment please?

**Comment by stx** [comment]
@JaffaKetchup Sure thing. I'll take a look at this tomorrow.

**Comment by stx** [comment]
@JaffaKetchup @ibrierley Tested this on web and mobile and took 60 FPS captures and went through it frame by frame and it looks fixed and side-effect free! Nice work.

**Review by JaffaKetchup — APPROVED** [review]
Thanks @stx, no worries about the delay! LGTM.

**Pull request merged**
