### PR TITLE
Upgraded flutter + package versions

### PR DESCRIPTION
**Pull request by jopmiddelkamp**
In this PR I've upgraded the packages used in the `flutter_map` plugin and the updated the example project to match the latest version of `flutter create`.

### CODE REVIEW

**Comment by kengu** [comment]
@jopmiddelkamp PR #683 was merged yesterday, which I believe does the same thing. The only significant difference is that you have upgraded the dependencies also. Would you like to update this PR to align it with #683?

**Comment by JaffaKetchup** [comment]
Hi @jopmiddelkamp,
What needs to be done here to get this ready for merging? I'm referring to https://github.com/fleaflet/flutter_map/pull/793#issuecomment-802761776 and maybe that the dependencies can be even newer now?

**Comment by jopmiddelkamp** [comment]
> @jopmiddelkamp PR #683 was merged yesterday, which I believe does the same thing. The only significant difference is that you have upgraded the dependencies also. Would you like to update this PR to align it with #683?

Yes seems like it did the same thing.

**Comment by JaffaKetchup** [comment]
Ok, thanks for your contribution! Will close now.

**Pull request closed without merging**
