### PR TITLE
#1119: fix LateInitializationError with polylineCulling

### PR DESCRIPTION
**Pull request by jithware**
See #1119

### CODE REVIEW

**Review by ibrierley — COMMENTED** [review]
I think this makes sense!

**Comment by jithware** [comment]
Review and approval required by reviewers with write access. Any one willing to review and approve?

**Comment by jithware** [comment]
See https://github.com/fleaflet/flutter_map/discussions/1117

**Review by JaffaKetchup — APPROVED** [review]
Changes to examples. Simple change to public API. LGTM.

@jithware Please pull upstream when possible, then I (or another maintainer) can merge.

**Comment by jithware** [comment]
@JaffaKetchup should be all set. Let me know of any problems.

**Pull request merged**
