### PR TITLE
chore: bump versions of workflow actions, add to dependabot

### PR DESCRIPTION
**Pull request by josxha**
removes all these depcrecation warnings

image

### CODE REVIEW

**Review by JaffaKetchup — APPROVED** [review]
LGTM, feel free to merge when you're ready.

**Comment by josxha** [comment]
Thanks for the approval. There is still one warning, it could be though that it's because I made the PR from a fork, idk. I'll try to fix it tomorrow. 👍

image

**Comment by JaffaKetchup** [comment]
Yeah, it's all good. It's because it's from a fork, it can't use the API to post the friendly-text summary report. It still runs and checks the score just fine though.

**Comment by josxha** [comment]
Alright in that case I guess this warning should fix itself once merged.

**Pull request merged**
