### PR TITLE
Improve readme when using mapbox

### PR DESCRIPTION
**Pull request by comatory**

### CODE REVIEW

**Comment by comatory** [comment]
https://github.com/fleaflet/flutter_map/issues/1029

**Review by ibrierley — APPROVED** [review]

**Review by ibrierley — APPROVED** [review]

**Comment by comatory** [comment]
@ibrierley I'm not allowed to merge it even though you gave me approving review.

**Comment by ibrierley** [comment]
No problem, just thought I'd add a review in case it helped someone who has write access.

**Review by JaffaKetchup — APPROVED** [review]
Simple README addition. LGTM.

**Comment by JaffaKetchup** [comment]
Ready to merge.

This is a documentation update: please note #992 which will eventually improve documentation and may or may not replace the README. Therefore, if applicable, this change will also be carried (in the best way possible) to the new documentation.

**Pull request merged**
