### PR TITLE
fix: `LateInitializationError` when specifying `initialCameraFit`

### LINKED ISSUE #1684: [BUG] LateInitializationError when specifying `initialCameraFit`
### What is the bug?

When running the sample code that includes `initialCameraFit`, `LateInitializationError` is thrown.
<details>
<summary>Console output</summary>

```console
════════ Exception caught by widgets library ═══════════════════════════════════
The following LateError was thrown building LayoutBuilder:
LateInitializationError: Field '_interactiveViewerState@628435804' has not been initialized.

The relevant error-causing widget was
FlutterMap
main.dart:29
When the exception was thrown, this was the stack
#0      FlutterMapInternalController._interactiveViewerState (package:flutter_map/src/map/controller/internal.dart)
#1      FlutterMapInternalController._emitMapEvent
internal.dart:461
#2      FlutterMapInternalController.move
internal.dart:98
#3      FlutterMapInternalController.fitCamera
internal.dart:244
#4      _FlutterMapStateContainer._applyInitialCameraFit
widget.dart:212
#5      _FlutterMapStateContainer.build.<anonymous closure>
widget.dart:145
#6      _LayoutBuilderElement._layout.layoutCallback
layout_builder.dart:119
#7      BuildOwner.buildScope
framework.dart:2719
#8      _LayoutBuilderElement._layout
layout_builder.dart:153
#9      RenderObject.invokeLayoutCallback.<anonymous closure>
object.dart:2604
#10     PipelineOwner._enableMutationsToDirtySubtrees
object.dart:1059
#11     RenderObject.invokeLayoutCallback
object.dart:2604
#12     RenderConstrainedLayoutBuilder.rebuildIfNecessary
layout_builder.dart:228
#13     _RenderLayoutBuilder.performLayout
layout_builder.dart:313
#14     RenderObject.layout
object.dart:2493
#15     RenderBox.layout
box.dart:2382
#16     RenderProxyBoxMixin.performLayout
proxy_box.dart:104
#17     RenderObject.layout
object.dart:2493
#18     RenderBox.layout
box.dart:2382
#19     RenderConstrainedBox.performLayout
proxy_box.dart:279
#20     RenderObject.layout
object.dart:2493
#21     RenderBox.layout
box.dart:2382
#22     RenderPadding.performLayout
shifted_box.dart:238
#23     RenderObject.layout
object.dart:2493
#24     RenderBox.layout
box.dart:2382
#25     RenderProxyBoxMixin.performLayout
proxy_box.dart:104
#26     RenderObject.layout
object.dart:2493
#27     RenderBox.layout
box.dart:2382
#28     RenderProxyBoxMixin.performLayout
proxy_box.dart:104
#29     RenderObject.layout
object.dart:2493
#30     RenderBox.layout
box.dart:2382
#31     RenderSliverFixedExtentBoxAdaptor.performLayout
sliver_fixed_extent_list.dart:240
#32     RenderObject.layout
object.dart:2493
#33     RenderSliverEdgeInsetsPadding.performLayout
sliver_padding.dart:139
#34     _RenderSliverFractionalPadding.performLayout
sliver_fill.dart:160
#35     RenderObject.layout
object.dart:2493
#36     RenderViewportBase.layoutChildSequence
viewport.dart:534
#37     RenderViewport._attemptLayout
viewport.dart:1512
#38     RenderViewport.performLayout
viewport.dart:1421
#39     RenderObject._layoutWithoutResize
object.dart:2332
#40     PipelineOwner.flushLayout
object.dart:1013
#41     RendererBinding.drawFrame
binding.dart:494
#42     WidgetsBinding.drawFrame
binding.dart:918
#43     RendererBinding._handlePersistentFrameCallback
binding.dart:360
#44     SchedulerBinding._invokeFrameCallback
binding.dart:1297
#45     SchedulerBinding.handleDrawFrame
binding.dart:1227
#46     SchedulerBinding._handleDrawFrame
binding.dart:1085
#47     _invoke (dart:ui/hooks.dart:170:13)
#48     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
#49     _drawFrame (dart:ui/hooks.dart:140:31)
════════════════════════════════════════════════════════════════════════════════
```
</details>

### How can we reproduce it?

<details>
<summary>Sample Code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Center(
          child: MyWidget(),
        ),
      ),
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      height: 250,
      color: Colors.grey.shade100,
      child: FlutterMap(
        options: MapOptions(
          initialCameraFit: CameraFit.bounds(
            bounds: LatLngBounds.fromPoints(
              [
                const LatLng(0, 0),
                const LatLng(10, 0),
              ],
            ),
          ),
        ),
        children: [
          TileLayer(
            errorImage: Image.memory(base64Decode(
                    'iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAQAAAD2e2DtAAABnElEQVR42u3SQQEAAAQEMJdcdF5S2DIs08VjEUAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAAAQQQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQAAEQQAABBEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAABEAAzgLXe38QsfcE+gAAAABJRU5ErkJggg=='))
                .image,
            fallbackUrl: '',
            tileProvider: NetworkTileProvider(),
            urlTemplate: '',
            tileSize: 256,
          ),
        ],
      ),
    );
  }
}
```
</details>

### Do you have a potential solution?

Moving the `initialCameraFit` code to the `onMapReady` function can be an alternative approach.
```dart
onMapReady: () {
  _mapController.fitCamera(
    CameraFit.bounds(
      bounds: LatLngBounds.fromPoints(
        [
          const LatLng(0, 0),
          const LatLng(10, 0),
        ],
      ),
    ),
  );
},
```

### Platforms

iOS

### Severity

Erroneous: Prevents normal functioning and causes errors in the console

### PR DESCRIPTION
**Pull request by TesteurManiak**
Fix #1684

### CODE REVIEW

**Review by JaffaKetchup — CHANGES_REQUESTED** [review]
Well this is strange. It seems to work, sometimes. Testing on Windows.
If I put it on my main display, it works correctly. If I put it on my secondary display, regardless of where VS Code is (so window focus isn't an issue), it still centers over Russia and never applies the camera fit.
Not sure if this is related to this, or there's some other reason why it refuses to fit, but I'm using the following fits:
```dart
initialCameraFit: CameraFit.insideBounds(
  bounds: LatLngBounds(
    const LatLng(-90, -180),
    const LatLng(90, 180),
  ),
),
cameraConstraint: CameraConstraint.contain(
  bounds: LatLngBounds(
    const LatLng(-90, -180),
    const LatLng(90, 180),
  ),
),
```

**Comment by TesteurManiak** [comment]
With such an inconsistent behavior with no clear reason I'm starting to think that maybe we should remove the `initialCameraFit` and advise to perform a `fitCamera` in the `onMapReady` callback until we re-implement it properly 🤔 
But no matter what we shouldn't let a runtime exception such as this `LateInitializationError` going in the package.

**Comment by JaffaKetchup** [comment]
Can't we just call the methods in the same place as `onMapReady`?

I'm very surprised at this behaviour as well, so I'm going to unplug my primary display and just use my laptop screen to see if that resolves the issue as well.

**Comment by TesteurManiak** [comment]
@JaffaKetchup @ibrierley I've made a small update, now `_applyInitialCameraFit` is triggered in the same `WidgetsBinding.instance.addPostFrameCallback` as `_updateAndEmitSizeIfConstraintsChanged`, for me it has been working pretty well.

**Comment by JaffaKetchup** [comment]
Here's something even stranger. Whether `initialCenter` and `initialZoom` are defined and have any effect is different between the two window sizes:

https://github.com/fleaflet/flutter_map/assets/58115698/bb6df4ee-9cbb-41e8-b847-d5868fb51bb6

It can only assume there is some weird Flutter bug, or something else weird going on, so I think we have to just forget about this issue.

**Comment by JaffaKetchup** [comment]
If someone else can verify and approve, that'd be great, as I don't want this to affect the results in any way.

**Comment by TesteurManiak** [comment]
> It can only assume there is some weird Flutter bug, or something else weird going on, so I think we have to just forget about this issue.

Yeah I think we should consider first that this PR will solve the `LateInitializationError` and take time to investigate this weird behavior in a separate issue if we can reproduce it accurately to confirm if it's coming from the Flutter framework or is due to the big state refactor the package had.

**Comment by JaffaKetchup** [comment]
Agreed. It's worth noting that this issue doesn't happen in the v5 example app home page, with the equivalent modifications.

**Pull request merged**
