### PR TITLE
Add 'isFilled' field to Polygon class, fix issue with polygons doted border drawing and created example page for Polygons

### PR DESCRIPTION
**Pull request by BaptistePires**
Hello, 
First of all, thanks for this awesome package, I find it really usefull.

I added a new field in the Polygon class to allow users to fill or not the polygon, it's called `isFilled` (by default it's false, so it wont change the behavior of current applications that may be working with Polygons) and it's checked in the `PolygonPainter` class : 

       final paint = Paint()

      ..style = polygonOpt.isFilled ? PaintingStyle.fill : PaintingStyle.stroke  

      ..color = polygonOpt.color;  

When I was doing that, I found that when I was drawing polygons with doted borders, the 
last one was not doted, I fixed that by updating the method `_paintDottedLine`, 
I only updated those lines :
`for (var i = 0; i < offsets.length - 1; i++){`
`    var o0 = offsets[i];`
`    var o1 = offsets[i + 1];`
Now it's : 
`for (var i = 0; i < offsets.length; i++){`
`    var o0 = offsets[i % offsets.length];`
`    var o1 = offsets[(i + 1) % offsets.length];`
Thank's to that, when it's `i + 1` it takes `offsets[0]` and draw the line between the last and the first point.

I also added an example page for the polygon as there was not.

Here are some screenshots to explain what I said : 

- The new drawer (Just added 'Polygons' under 'Polylines') : https://ibb.co/DbHnjh2
- The Polygon examples : https://ibb.co/37zMZ3p (and there is one with the doted borders issue : https://ibb.co/7bmQJhJ)
- One rectangle with the doted borders issue : https://ibb.co/sFSRDtk
- With the fix I made : https://ibb.co/M7H53VD

If you need any other information, I'll provide it.

Thanks for reading !

### CODE REVIEW

**Comment by johnpryan** [comment]
LGTM - could you take a look at the [travis build](https://travis-ci.org/johnpryan/flutter_map/builds/640955275?utm_source=github_status&utm_medium=notification) failures and fix the merge conflicts?

**Comment by BaptistePires** [comment]
Alright, I have a lot of stuff going on, I'll fix this near feb 3

**Comment by BaptistePires** [comment]
The conflicts seem resolved, but the Travis CI build fail does not seem to be related to my code, I did not updated  lib/src/layer/tile_provider/tile_provider.dart

**Comment by BaptistePires** [comment]
I have checked again and I can't find why the Travis build failed, I ran dartfmt with Android Studio on the whole project, but nothing was updated

**Comment by johnpryan** [comment]
polygon_layer.dart has a new `_paintBorder` method, can you take a look at the merge conflicts?

The CI build is failing due to a lint rule  `flutter analyze` should show the lint.

**Comment by kengu** [comment]
@Wyseh Can you resolve these conflicts? If not, should we close the PR?

**Comment by Wyseh** [comment]
I'll try to take some time to do it during this week but I currently have a lot of work, if it's not done within this week you can close it

**Comment by S-Man42** [comment]
Any progress here? Would love to see this feature :)

**Comment by ibrierley** [comment]
This was a long time ago, but makes sense to me...is this still an issue and a PR that's wanted ? (If so I think you need to repull upstream I think and see if its still ok)

**Comment by S-Man42** [comment]
Still required. When implementing, you maybe think about https://github.com/fleaflet/flutter_map/issues/972 this as well (Border Color different from filled color)

**Comment by ibrierley** [comment]
Yes, some of the original poly options on that aren't too clear on that for me (maybe that's also a docs issue). I've previously wondered whether the polyline/polygon needs some further development that could be done as a plugin with new options  and features (so as not to break the current usage), but maybe that's a good discussion to have.

**Comment by aytunch** [comment]
Is this going to be merged friends?
This is a nice addition

**Comment by JaffaKetchup** [comment]
@BaptistePires Can you pull upstream so I can take a look? Thanks!

**Comment by S-Man42** [comment]
Any progess here?

**Comment by JaffaKetchup** [comment]
Just need @BaptistePires to pull upstream, then ready for review.

**Comment by BaptistePires** [comment]
Hi, I've been very busy this year, and I really didn't have time to take care of this, I'll try to get it done by the end of the week. Sorry for the inconvenience.

**Comment by JaffaKetchup** [comment]
No problem!

**Comment by BaptistePires** [comment]
I resolved the conflicts but I wasn't able to test it yet, I'll come back as soon as I've tested it.

**Comment by JaffaKetchup** [comment]
It appears not all files are formatted correctly, can you run `dart format . --fix` just to make sure (when you're ready). Many thanks!

**Comment by BaptistePires** [comment]
As this PR is quite old, I'll have to update my code to

**Comment by BaptistePires** [comment]
I was able to test it and it's working on my device

**Comment by JaffaKetchup** [comment]
Thanks, I'll test it soon as well, and hopefully I can merge.

**Comment by JaffaKetchup** [comment]
I am testing right now. Quick question, did you have problems compiling the example app for Android? I don't think it's your fault, but I can't do it for some reason. (I've noticed it before as well.) Using web for now.

**Review by JaffaKetchup — APPROVED** [review]
LGTM. I'm not sure why the Android app isn't compiling for me, but that can be fixed for another time.
Will merge now. Thanks for your contribution!

**Comment by BaptistePires** [comment]
Yes I had issues related to the minSdkVersion iirc, I thought it was because my environment was a bit old.
Thanks a lot!

**Comment by sjoulbak** [comment]
@JaffaKetchup While upgrade this package from 0.14.0 to 1.0.0, we found out that our polygons weren't filled anymore by default. Perhaps it could be helpful to add this to the changelog or change the default value of `isFilled` from `false` to `true`?

**Comment by ibrierley** [comment]
Yes, good spot. I don't think we should change this now though. Updating to 1.0.0 should be ok to have breaking changes..it just shouldn't have had a change before that, and I guess changing it back will introduce a breaking change again when there shouldn't be any :D. (I think I sound as clear as mud on that).

It should get added to changelog though (and we should try and watch out for things like that in the future better).

**Pull request merged**
