### PR TITLE
Re-expose `MapControllerImpl`

### PR DESCRIPTION
**Pull request by JosefWN**
Simple proposal for https://github.com/fleaflet/flutter_map/issues/1544.

In line with `v4.0.0` behavior. Tried and it works with my custom map controller.

### CODE REVIEW

**Review by TesteurManiak — APPROVED** [review]
LGTM! @JaffaKetchup was there any specific reason to make this constructor private in v5?

**Comment by JaffaKetchup** [comment]
@TesteurManiak No reason other than cleanup of external APIs.

Btw, doesn't it seem redundant to even have this separation anyway (between impl and standard), if they're always exposed together? If they're not merged, we need to copy the docs across to ensure better docs coverage.

**Comment by TesteurManiak** [comment]
Yeah the separation between `MapController` and `MapControllerImpl` is redundant to me too. I don't see why they couldn't be merged into one `MapController` class, that would probably make more sens.

**Review by JaffaKetchup — CHANGES_REQUESTED** [review]
I think that should be done then.

**Comment by JaffaKetchup** [comment]
@JosefWN I'm not 100% sure what you mean by that I'm afraid!

**Comment by JaffaKetchup** [comment]
> I suppose it boils down to whether we think that `MapControllerImpl` will grow larger over time.

Given that #1549 was only recently opened to add new functionality, I think we have to assume it might change.

> because merging them would impose needlessly strict and potentially "clunky" constraints on any extension of MapControllerImpl vs an implementation of MapController.

However, I'm not sure it's needless. Anyway, if we move the implementation methods into the current `MapController`, and make it a `base` (`abstract`?) class, extenders still don't have to implement all methods - they can just override ones important to them, or add new ones? They can also override all getters and variables.

Perhaps I'm missing something. But I do understand that extension/implementation is different.

I would also like @mootw and @ibrierley s' inputs to this!

**Comment by ibrierley** [comment]
I think I'm kind of indifferent on this one, as I never quite understood why it was designed in the way it was originally, so don't feel that aware to spot any issues.

**Comment by rorystephenson** [comment]
My 2 cents (sorry it's late here and I don't have time to read this all now):

I prefer to keep the API size as small as possible by only exposing what we want to which in turn makes refactoring much easier. For that reason I am for keeping MapControllerImpl and not exporting it to hides methods/variables we don't want to expose (like the stream sink or the setter for the map state for example). If there is another way to achieve the same thing I'm all for it.

Again I haven't had time to read this or even check the PR changes and it's laaate here so I this may already be addressed.

**Comment by JaffaKetchup** [comment]
Converting to a draft for now. Let's see how #1551 plays out first!

**Comment by JaffaKetchup** [comment]
@rorystephenson @JosefWN With #1551 now merged, what needs to happen here (if anything)?

**Comment by rorystephenson** [comment]
My vote is to close this and leave things as-is and close this. If we can find a more elegant way to allow extending MapController without exposing MapControllerImpl that would be great but for now it doesn't look like it.

**Comment by JaffaKetchup** [comment]
Maybe we can export impl through the plugins API import? Doesn't make much of a difference, but at least it would be something.

If not, I'm happy to close this.

**Comment by rorystephenson** [comment]
We don't want the MapControllerImpl to be available even to plugins. It gives access to methods which should only be used by flutter_map internals.

I've upgraded the latest version of flutter_map_animations which wraps the MapController and I think it's an elegant solution. IMO we can close this PR.

**Comment by JaffaKetchup** [comment]
Ok. We'll close for now, but if anyone has any objections, just ask for this to be reopened.

**Pull request closed without merging**
