### PR TITLE
perf: avoid caching a single multiplication

### PR DESCRIPTION
**Pull request by mootw**
avoids caching a single multiplication operation. converts all toRadians and other helpers to use vector_math constant. (part of reducing dependency on latlong2).

### CODE REVIEW

**Review by TesteurManiak — APPROVED** [review]
LGTM!

**Review by JaffaKetchup — CHANGES_REQUESTED** [review]
Some files import '_64', some don't? Is that intentional?

**Comment by josxha** [comment]
As far as I can see had `vector_math` as a dependency but it was not used anywhere?
This PR introduces the use of it for the `degrees2Radians` constant. Are there additional use cases in the future? If not I'd prefer to remove the dependency entirely and add the const to flutter_map directly. 

Long terms I think it should be used from a future latlong package but not the current implementation of `latlong2`.

**Comment by JaffaKetchup** [comment]
I would agree with @josxha here - adding a dependency just for this seems a little bit too much.

**Comment by mootw** [comment]
vector_math is a core flutter dependency, and we already use it in camera.dart for the matrix transform at line 301, we just don't explicitly depend on it. Matrix4 is exposed by `package:flutter/material.dart`

**Review by JaffaKetchup — APPROVED** [review]
LGTM! I suppose that we indirectly depend on it anyway, so no harm in depending on it directly as well.

Would be great if you could resolve the conflicts as well :D.

**Review by josxha — APPROVED** [review]
thanks for the explanation. pr lgtm

**Comment by JaffaKetchup** [comment]
(@josxha feel free to cherry pick)

**Comment by JaffaKetchup** [comment]
> np! also, we could consider using the aabb2 and other methods from vector_math in the future for things like bounding boxes and transforms!

Yep, that would make sense.

**Pull request merged**
