### PR TITLE
Center scroll wheel zoom on mouse pointer

### PR DESCRIPTION
**Pull request by pmjobin**
This modifies the behaviour of scroll wheel zooming so that it mimics other map packages (such as Google Maps) by pinning the center of scaling under the mouse pointer. This works regardless of the rotation of the map.

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
@pmjobin Will try to test soon. Thanks for your contribution!

**Review by JaffaKetchup — CHANGES_REQUESTED** [review]
To be able to merge this, the checks need to be satisfied. To do this, please run `dart format . --fix` in your console.

**Comment by JaffaKetchup** [comment]
@pmjobin @a14n How will #1191 and #1182 work together? Will they interfere?

**Comment by pmjobin** [comment]
Fixed.

**Review by JaffaKetchup — CHANGES_REQUESTED** [review]
Sorry to keep annoying you! This also needs to be fixed to appease the checks:

```
lib/src/gestures/gestures.dart:3:[8] - unused-import - Unused import: 'dart:math'. Try removing the import directive. 
```

**Review by JaffaKetchup — COMMENTED** [review]
Will test changes soon, now auto-checks are all good :)

**Comment by pmjobin** [comment]
Thanks for your help!

**Review by ibrierley — APPROVED** [review]
Nice work and thanks! Tests good for me with and without rotation in chrome and android.

**Comment by JaffaKetchup** [comment]
Testing now...
Will have to resolve those conflicts before merge.

**Comment by a14n** [comment]
To resolve the conflict you have to replace `MapEventSource.custom` with `MapEventSource.scrollWheel`

**Review by JaffaKetchup — APPROVED** [review]
LGTM, seems to work.

**Pull request merged**
