### PR TITLE
Update Version

### PR DESCRIPTION
**Pull request by JaffaKetchup**
- Updated version (in pubspec.yaml) to 1.0.0 - semantic versioning
- Fixed README broken link

### CODE REVIEW

**Comment by ibrierley** [comment]
I'm fine with this unless any other objections from folks, especially other maintainers. It's not really a breaking change version, but now feels like a reasonable time where there has been a fair few changes, fixes, improvements etc and things feel stable.

I'd be happy for others to do a bit of testing on latest code and try and spot any flaws first, so maybe see if any objections within a week or so ?

**Comment by pablojimpas** [comment]
The change in the plugin API from Stream<Null> to Stream<void> is in fact a breaking change, but I think that in semantic versioning all the versions below 1.0.0 do not have any guarantees in terms of API stability.

Marking a 1.0 release means that the package API it's stable and every breaking change down the road will mean increasing the major version number.

I'm not a fan of packages that say they're above stable (above 1.0.0) but break the API once or twice a year releasing new major versions, I'll suggest to make this move only if you're sure that no breaking changes will be needed to improve the package in the short/mid-term.

**Comment by JaffaKetchup** [comment]
Hi @pablojimpas,

Thanks for your concerns, and you've made a good point about increasing major number for every breaking change.
The way flutter_map has been working is essentially to ignore the first number, use the second number as major and breaking, and third number as minor/patch. Therefore, technically flutter_map will be on 15.0.0, but I'm using 1.0.0 because you usually start from scratch when switching versioning systems.

What do you mean by Stream to Stream in the public API, I might have misunderstood something?

Thanks.

**Comment by pablojimpas** [comment]
> What do you mean by Stream to Stream in the public API, I might have misunderstood something?

Sorry, the angle brackets broke formatting: `Stream<Null>` to `Stream<void>`

> Therefore, technically flutter_map will be on 15.0.0, but I'm using 1.0.0 because you usually start from scratch when switching versioning systems.

Okey, I like that.

**Comment by ibrierley** [comment]
It's an interesting point about the Null vs Void Stream change. That one passed by by, because it was a lint change. One to watch out for in future.

**Comment by ibrierley** [comment]
Just thinking a bit more on this, I feel like we should probably do a bit of work on the Changelog about previous changes first ? Maybe it's not so clear to others about recent changes that have happened, if it impacts them etc, what to watch out for.

**Comment by JaffaKetchup** [comment]
Yeah, good idea as it hasn't been changed in ages. I'm happy to add it to this PR, and happy for you to add anything as well :)

**Comment by JaffaKetchup** [comment]
Made those changes to the CHANGELOG. It was incredibly out of date: took over an hour to collate all the changes, authors, and PR/issue links! Let me know if anything needs changing.
I also updated the pubspec package description whilst I was at it, as it's very out of date compared to the latest one at the top of the README.

**Comment by ibrierley** [comment]
Great stuff! I hadn't quite appreciated how many there were actually, they do stack up.

I'll try and take a better look over the weekend, but I suspect I won't have a lot to add.

**Comment by pablojimpas** [comment]
Awesome work, actually making this changelog could help with https://github.com/fleaflet/flutter_map/issues/1188 since last time @johnpryan appeared to make a new release he asked for a detailed changelog to stay up to date with the recent activity https://github.com/fleaflet/flutter_map/issues/1021#issuecomment-917148158

**Comment by JaffaKetchup** [comment]
If everyone here is happy to merge this, I think it's pretty much finished.

**Comment by ibrierley** [comment]
Happy with the changelog, all looks good to me!

**Comment by JaffaKetchup** [comment]
(@ibrierley Can't merge without a review if that's what you were intending :))

**Review by ibrierley — COMMENTED** [review]
I think the changelog works is great, thanks for all of that! Just wondering actually before approving, should we mark placeholderImage as deprecated (as it doesn't work currently and seems to have been noted at that in the past without any actual note of it anywhere) https://github.com/fleaflet/flutter_map/issues/1244 ? I'm fine either way, but maybe if we decide that it's not going to be fixed, it would be a point to mention it here ?

**Comment by JaffaKetchup** [comment]
Good point, just done it.

**Review by ibrierley — COMMENTED** [review]
Hah being pedantic now :D, maybe we should add placeholderImage deprecation to the changelog as well ? (even though it was kinda broken a long while back)

**Comment by JaffaKetchup** [comment]
I'm happy to do it, but I think we shouldn't as it's quite a minor (and now obvious to developers) deprecation and (as you mentioned) broken a long time ago. Happy to do it if you disagree though!

**Comment by ibrierley** [comment]
No problem!

**Review by ibrierley — APPROVED** [review]
lgtm.

**Pull request merged**
