### PR TITLE
Add stroke cap and join options to Polyline

### PR DESCRIPTION
**Pull request by calmh**
This just adds two options to the Polyline that otherwise require a plugin and copying most of the polyline rendering code.

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
This would be very useful for my plugin, so I hope it can be merged!

**Comment by calmh** [comment]
🤷

**Review by ibrierley — APPROVED** [review]
Looks good

**Comment by JaffaKetchup** [comment]
@calmh Please pull from upstream, then this is ready for merge. Thanks!

**Comment by calmh** [comment]
@JaffaKetchup done

**Pull request merged**
