### PR TITLE
feat: add `dottedSpacingFactor` to customize dotted polyline spacing

### PR DESCRIPTION
**Pull request by gnassro**
Now we can customize the space between dots if `isDotted=true`

### CODE REVIEW

**Comment by josxha** [comment]
Thanks for the pull request @gnassro! 
I did a quick test and your changes seem to work well.

There are some small things I would prefer to have changed:
- We have an open [feature request for dashed polylines](https://github.com/fleaflet/flutter_map/issues/1447). So it wood be good to have the name a bit more general like "segmentSpacingFactor" or somthing similar. Then we can use the parameter for dashed polyine too once the feature arrives.
- The CI checks show that the code is not formatted, you can do this with `dart format .`, but if you have difficulties I can do it for you if you want.


Then there are some general things I discovered while testing that <ins>you don't need to care about</ins> but are worth writing down:
- changing isDotted doesn't get picked up by hot reload
- It would be in general nice to have the dotted Polyline features represented in the example app, but I think that putting all on the polyline page would look cluttered.

**Comment by gnassro** [comment]
@josxha the only thing that I didn't understand is, what do you mean by `changing isDotted doesn't get picked up by hot reload` ?

**Review by JaffaKetchup — APPROVED** [review]
LGTM, thanks :). Will wait for a second review before merging.

**Comment by josxha** [comment]
Sorry for the delay, changes looking good. Thanks for updating the example app too.

> the only thing that I didn't understand is, what do you mean by changing isDotted doesn't get picked up by hot reload ?

This is a bug that is not related to this pull request. If you 
- run the app in debug mode
- change `isDotted: true,` to `isDotted: false,`
- trigger a hot reload

Then the polyline doesn't change it's appearance from a dotted to a normal line. A quick guess is because the polyline hashCode gets cached it doesn't regocnizes the change - but anyways as said it's not related to this pr.

Thanks a lot for the contribution!

**Review by josxha — APPROVED** [review]

**Pull request merged**
